### ISSUE TITLE
Is there any reason why the podspec is restricted to iOS?

### ISSUE THREAD

**Issue by tonyarnold** [sharplet/EnumeratorKit#6]
Given that this library is mainly extensions to Foundation, would you consider removing the iOS limitation in the podspec?

**Comment by sharplet** [comment]
@tonyarnold If it's still relevant, free to test this out by pulling the master branch:

```ruby
pod "Kiwi", git: "https://github.com/sharplet/EnumeratorKit.git", branch: "master"
```

**Comment by tonyarnold** [comment]
Thanks @sharplet — I appreciate you adding this support.
